# \StudHunter\docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: studhunter-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - studhunter-db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: StudHunter.API/Dockerfile
    container_name: studhunter-api
    restart: always
    volumes:
      - studhunter-uploads:/app/wwwroot/uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=StudHunter
      - Jwt__Audience=StudHunterUsers
      - AllowedOrigins__0=http://studhunter.ru
      - AllowedOrigins__1=http://www.studhunter.ru
      - AllowedOrigins__2=http://138.16.179.191
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: studhunter-ui
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  studhunter-db-data:
  studhunter-uploads: