// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudHunter.DB.Postgres;

#nullable disable

namespace StudHunter.DB.Postgres.Migrations
{
    [DbContext(typeof(StudHunterDbContext))]
    [Migration("20260207132505_Attempt1")]
    partial class Attempt1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.AdditionalSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AdditionalSkills");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.BlackList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("BlockedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("BlockedUserId")
                        .HasColumnType("UUID");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UUID");

                    b.HasKey("Id");

                    b.HasIndex("BlockedUserId");

                    b.HasIndex("UserId", "BlockedUserId")
                        .IsUnique();

                    b.ToTable("BlackLists", t =>
                        {
                            t.HasCheckConstraint("CK_BlackList_NotSelfBlock", "\"UserId\" <> \"BlockedUserId\"");
                        });
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("UUID");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("UUID");

                    b.HasKey("Id");

                    b.HasIndex("User2Id");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f8e833b-8f9b-4b2a-9e1d-3b5a1f2c4d5e"),
                            Name = "Челябинск"
                        });
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("EmployerId")
                        .HasColumnType("UUID");

                    b.Property<Guid?>("ResumeId")
                        .HasColumnType("UUID");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UUID");

                    b.Property<Guid?>("VacancyId")
                        .HasColumnType("UUID");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("ResumeId");

                    b.HasIndex("UserId");

                    b.HasIndex("VacancyId");

                    b.HasIndex("UserId", "EmployerId")
                        .IsUnique()
                        .HasFilter("\"EmployerId\" IS NOT NULL");

                    b.HasIndex("UserId", "ResumeId")
                        .IsUnique()
                        .HasFilter("\"ResumeId\" IS NOT NULL");

                    b.HasIndex("UserId", "VacancyId")
                        .IsUnique()
                        .HasFilter("\"VacancyId\" IS NOT NULL");

                    b.ToTable("Favorites", t =>
                        {
                            t.HasCheckConstraint("CK_Favorite_AtLeastOneTarget", "\"VacancyId\" IS NOT NULL OR \"EmployerId\" IS NOT NULL OR \"ResumeId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("UUID");

                    b.Property<Guid?>("ResumeId")
                        .HasColumnType("UUID");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("UUID");

                    b.Property<string>("SnapshotReceiverName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SnapshotSenderName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SnapshotVacancyTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("VacancyId")
                        .HasColumnType("UUID");

                    b.HasKey("Id");

                    b.HasIndex("ExpiredAt")
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("ResumeId");

                    b.HasIndex("SenderId");

                    b.HasIndex("VacancyId");

                    b.HasIndex("SenderId", "ReceiverId", "Status")
                        .IsUnique()
                        .HasDatabaseName("IX_Unique_Active_General_Offer")
                        .HasFilter("\"Status\" = 0 AND \"VacancyId\" IS NULL");

                    b.HasIndex("SenderId", "ReceiverId", "VacancyId", "Status")
                        .IsUnique()
                        .HasDatabaseName("IX_Unique_Active_Invitation")
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("UUID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("UUID");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("UUID");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("UUID");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("InvitationId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SentAt");

                    b.HasIndex("ReceiverId", "IsRead");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UUID");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.OrganizationDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActualAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("UUID");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("VARCHAR(12)");

                    b.Property<string>("Kpp")
                        .HasMaxLength(9)
                        .HasColumnType("VARCHAR(9)");

                    b.Property<string>("LegalAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ogrn")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR(15)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId")
                        .IsUnique();

                    b.HasIndex("Inn")
                        .IsUnique();

                    b.ToTable("OrganizationDetails", (string)null);
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BOOLEAN")
                        .HasDefaultValue(false);

                    b.Property<Guid>("StudentId")
                        .HasColumnType("UUID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.ResumeAdditionalSkill", b =>
                {
                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdditionalSkillId")
                        .HasColumnType("uuid");

                    b.HasKey("ResumeId", "AdditionalSkillId");

                    b.HasIndex("AdditionalSkillId");

                    b.ToTable("ResumeAdditionalSkills");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.StudyDirection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StudyDirections");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.StudyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CourseNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("UUID");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("UUID");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BOOLEAN")
                        .HasDefaultValue(false);

                    b.Property<Guid>("StudentId")
                        .HasColumnType("UUID");

                    b.Property<Guid?>("StudyDirectionId")
                        .HasColumnType("UUID");

                    b.Property<int>("StudyForm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("UniversityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("StudyDirectionId");

                    b.HasIndex("UniversityId");

                    b.ToTable("StudyPlans");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.StudyPlanCourse", b =>
                {
                    b.Property<Guid>("StudyPlanId")
                        .HasColumnType("UUID");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.HasKey("StudyPlanId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudyPlanCourses");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("UUID");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BOOLEAN")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int>("RegistrationStage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Vacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("UUID");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BOOLEAN")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("Salary")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10, 2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.ToTable("Vacancies", t =>
                        {
                            t.HasCheckConstraint("CK_Vacancy_Salary", "\"Salary\" >= 0 AND \"Salary\" <= 1000000");
                        });
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.VacancyAdditionalSkill", b =>
                {
                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdditionalSkillId")
                        .HasColumnType("uuid");

                    b.HasKey("VacancyId", "AdditionalSkillId");

                    b.HasIndex("AdditionalSkillId");

                    b.ToTable("VacancyAdditionalSkills");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.VacancyCourse", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid");

                    b.HasKey("CourseId", "VacancyId");

                    b.HasIndex("VacancyId");

                    b.ToTable("VacancyCourses");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Administrator", b =>
                {
                    b.HasBaseType("StudHunter.DB.Postgres.Models.User");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TIMESTAMPTZ");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Employer", b =>
                {
                    b.HasBaseType("StudHunter.DB.Postgres.Models.User");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Student", b =>
                {
                    b.HasBaseType("StudHunter.DB.Postgres.Models.User");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("DATE");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsForeign")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.BlackList", b =>
                {
                    b.HasOne("StudHunter.DB.Postgres.Models.User", "BlockedUser")
                        .WithMany()
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudHunter.DB.Postgres.Models.User", "User")
                        .WithMany("BlackLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Chat", b =>
                {
                    b.HasOne("StudHunter.DB.Postgres.Models.User", "User1")
                        .WithMany("ChatsAsUser1")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudHunter.DB.Postgres.Models.User", "User2")
                        .WithMany("ChatsAsUser2")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Favorite", b =>
                {
                    b.HasOne("StudHunter.DB.Postgres.Models.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StudHunter.DB.Postgres.Models.Resume", "Resume")
                        .WithMany()
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StudHunter.DB.Postgres.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudHunter.DB.Postgres.Models.Vacancy", "Vacancy")
                        .WithMany()
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employer");

                    b.Navigation("Resume");

                    b.Navigation("User");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Invitation", b =>
                {
                    b.HasOne("StudHunter.DB.Postgres.Models.User", "Receiver")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudHunter.DB.Postgres.Models.Resume", "Resume")
                        .WithMany("Invitations")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudHunter.DB.Postgres.Models.User", "Sender")
                        .WithMany("SentInvitations")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudHunter.DB.Postgres.Models.Vacancy", "Vacancy")
                        .WithMany("Invitations")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Receiver");

                    b.Navigation("Resume");

                    b.Navigation("Sender");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Message", b =>
                {
                    b.HasOne("StudHunter.DB.Postgres.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudHunter.DB.Postgres.Models.Invitation", "Invitation")
                        .WithMany()
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudHunter.DB.Postgres.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudHunter.DB.Postgres.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chat");

                    b.Navigation("Invitation");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Notification", b =>
                {
                    b.HasOne("StudHunter.DB.Postgres.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.OrganizationDetail", b =>
                {
                    b.HasOne("StudHunter.DB.Postgres.Models.Employer", "Employer")
                        .WithOne("OrganizationDetails")
                        .HasForeignKey("StudHunter.DB.Postgres.Models.OrganizationDetail", "EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Resume", b =>
                {
                    b.HasOne("StudHunter.DB.Postgres.Models.Student", "Student")
                        .WithOne("Resume")
                        .HasForeignKey("StudHunter.DB.Postgres.Models.Resume", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.ResumeAdditionalSkill", b =>
                {
                    b.HasOne("StudHunter.DB.Postgres.Models.AdditionalSkill", "AdditionalSkill")
                        .WithMany("ResumeAdditionalSkills")
                        .HasForeignKey("AdditionalSkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudHunter.DB.Postgres.Models.Resume", "Resume")
                        .WithMany("AdditionalSkills")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdditionalSkill");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.StudyPlan", b =>
                {
                    b.HasOne("StudHunter.DB.Postgres.Models.Department", "Department")
                        .WithMany("StudyPlans")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudHunter.DB.Postgres.Models.Faculty", "Faculty")
                        .WithMany("StudyPlans")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudHunter.DB.Postgres.Models.Student", "Student")
                        .WithOne("StudyPlan")
                        .HasForeignKey("StudHunter.DB.Postgres.Models.StudyPlan", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudHunter.DB.Postgres.Models.StudyDirection", "StudyDirection")
                        .WithMany("StudyPlans")
                        .HasForeignKey("StudyDirectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudHunter.DB.Postgres.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Faculty");

                    b.Navigation("Student");

                    b.Navigation("StudyDirection");

                    b.Navigation("University");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.StudyPlanCourse", b =>
                {
                    b.HasOne("StudHunter.DB.Postgres.Models.Course", "Course")
                        .WithMany("StudyPlanCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudHunter.DB.Postgres.Models.StudyPlan", "StudyPlan")
                        .WithMany("StudyPlanCourses")
                        .HasForeignKey("StudyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("StudyPlan");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.User", b =>
                {
                    b.HasOne("StudHunter.DB.Postgres.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Vacancy", b =>
                {
                    b.HasOne("StudHunter.DB.Postgres.Models.Employer", "Employer")
                        .WithMany("Vacancies")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.VacancyAdditionalSkill", b =>
                {
                    b.HasOne("StudHunter.DB.Postgres.Models.AdditionalSkill", "AdditionalSkill")
                        .WithMany("VacancyAdditionalSkills")
                        .HasForeignKey("AdditionalSkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudHunter.DB.Postgres.Models.Vacancy", "Vacancy")
                        .WithMany("AdditionalSkills")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdditionalSkill");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.VacancyCourse", b =>
                {
                    b.HasOne("StudHunter.DB.Postgres.Models.Course", "Course")
                        .WithMany("VacancyCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudHunter.DB.Postgres.Models.Vacancy", "Vacancy")
                        .WithMany("Courses")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.AdditionalSkill", b =>
                {
                    b.Navigation("ResumeAdditionalSkills");

                    b.Navigation("VacancyAdditionalSkills");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Course", b =>
                {
                    b.Navigation("StudyPlanCourses");

                    b.Navigation("VacancyCourses");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Department", b =>
                {
                    b.Navigation("StudyPlans");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Faculty", b =>
                {
                    b.Navigation("StudyPlans");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Resume", b =>
                {
                    b.Navigation("AdditionalSkills");

                    b.Navigation("Invitations");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.StudyDirection", b =>
                {
                    b.Navigation("StudyPlans");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.StudyPlan", b =>
                {
                    b.Navigation("StudyPlanCourses");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.User", b =>
                {
                    b.Navigation("BlackLists");

                    b.Navigation("ChatsAsUser1");

                    b.Navigation("ChatsAsUser2");

                    b.Navigation("Favorites");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("SentInvitations");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Vacancy", b =>
                {
                    b.Navigation("AdditionalSkills");

                    b.Navigation("Courses");

                    b.Navigation("Invitations");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Employer", b =>
                {
                    b.Navigation("OrganizationDetails");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("StudHunter.DB.Postgres.Models.Student", b =>
                {
                    b.Navigation("Resume");

                    b.Navigation("StudyPlan");
                });
#pragma warning restore 612, 618
        }
    }
}
